import { execFile } from "node:child_process";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import type { GitHubClient } from "./github.ts";
import type { PullRequestContext } from "./types.ts";

const exec = promisify(execFile);
const FORBIDDEN = [
  /^\.git(?:\/|$)/,
  /(?:^|\/)\.env(?:\.|$)/,
  /\.(?:pem|key|p12|pfx)$/i,
  /(?:^|\/)(?:package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$/,
  /^\.github\/workflows\//,
];

export function validatePatchPaths(patch: string): string[] {
  if (!patch.trim()) throw new Error("The model returned an empty patch");
  const paths = new Set<string>();
  for (const line of patch.split("\n")) {
    const match = line.match(/^(?:---|\+\+\+) ([ab]\/)?(.+)$/);
    if (!match || match[2] === "/dev/null") continue;
    const path = match[2]!;
    if (path.startsWith("/") || path.split("/").includes("..") || path.includes("\0")) {
      throw new Error(`Unsafe patch path: ${path}`);
    }
    if (FORBIDDEN.some((pattern) => pattern.test(path))) throw new Error(`Patch modifies a forbidden path: ${path}`);
    paths.add(path);
  }
  if (paths.size === 0 || !patch.includes("diff --git ")) throw new Error("The response is not a unified git diff");
  return [...paths];
}

async function git(cwd: string, args: string[], env?: NodeJS.ProcessEnv): Promise<string> {
  const result = await exec("git", args, { cwd, env: { ...process.env, ...env }, maxBuffer: 20_000_000 });
  return result.stdout;
}

export async function createOrUpdateRemediation(
  github: GitHubClient,
  context: PullRequestContext,
  patch: string,
  summary: string,
  workspace: string,
): Promise<string> {
  validatePatchPaths(patch);
  const current = (await git(workspace, ["rev-parse", "HEAD"])).trim();
  if (current !== context.headSha) {
    throw new Error(`Checkout HEAD ${current} does not match Dependabot head ${context.headSha}`);
  }
  const directory = await mkdtemp(join(tmpdir(), "dependabot-review-"));
  const patchPath = join(directory, "remediation.diff");
  await writeFile(patchPath, patch, "utf8");
  await git(workspace, ["apply", "--check", "--whitespace=error", patchPath]);

  const branch = `dependabot-review/fix-${context.number}`;
  await git(workspace, ["checkout", "-B", branch, context.headSha]);
  await git(workspace, ["apply", "--whitespace=fix", patchPath]);
  await git(workspace, ["config", "user.name", "dependabot-review-action[bot]"]);
  await git(workspace, ["config", "user.email", "dependabot-review-action[bot]@users.noreply.github.com"]);
  await git(workspace, ["add", "--all"]);
  await git(workspace, ["commit", "-m", "Apply dependency update compatibility changes"]);
  const basic = Buffer.from(`x-access-token:${github.token}`).toString("base64");
  await git(workspace, [
    "-c", `http.https://github.com/.extraheader=AUTHORIZATION: basic ${basic}`,
    "push", "--force", "origin", `HEAD:refs/heads/${branch}`,
  ]);

  const existing = await github.findOpenPullRequest(branch, context.headRef);
  if (existing) return existing.html_url;
  const body = [
    `This PR applies compatibility changes identified while reviewing ${context.htmlUrl}.`,
    "",
    summary,
    "",
    `Base branch: \`${context.headRef}\``,
    "",
    "The patch was generated by AI and passed structural and `git apply --check` validation. Human review and normal CI are still required.",
  ].join("\n");
  return (await github.createPullRequest(branch, context.headRef, body)).html_url;
}
